export default{
    path:"/rebate",
    component:()=>import("views/rebate"),
    name:"rebate",
    redirect:"/rebate/all",
    children:[
        {
            path:"all",
            component:()=>import("components/all"),
            name:"all"
        },
        {
            path:"concert",
            component:()=>import("components/concert"),
            name:"concert"
        },
        {
            path:"musical",
            component:()=>import("components/musical"),
            name:"musical"
        },
        {
            path:"play",
            component:()=>import("components/play"),
            name:"play"
        },
        {
            path:"child",
            component:()=>import("components/child"),
            name:"child"
        },
        {
            path:"theater",
            component:()=>import("components/theater"),
            name:"theater"
        },
        {
            path:"opera",
            component:()=>import("components/opera"),
            name:"opera"
        },
        {
            path:"show",
            component:()=>import("components/show"),
            name:"show"
        },
        {
            path:"dance",
            component:()=>import("components/dance"),
            name:"dance"
        }
    ]
}